//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BinarySearchTree : BinaryTree
{
	public virtual void Insert()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Erase()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Find()
	{
		throw new System.NotImplementedException();
	}

}

