//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BinaryTreeNode {
    public virtual IComparable Data {
        get;
        set;
    }

    public virtual BinaryTreeNode LeftNode {
        get;
        set;
    }

    public virtual BinaryTreeNode RightNode {
        get;
        set;
    }

    public BinaryTreeNode() {
    }

    public BinaryTreeNode(IComparable data) {
        this.Data = data;
    }

}

