//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BinaryTree
{
	public virtual BinaryTreeNode BinaryTreeNode
	{
		get;
		set;
	}

	public virtual void GetLeftSubtree()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetRightSubtree()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetData()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

}

