//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BinaryTree {
    public virtual BinaryTreeNode BinaryTreeNode {
        get;
        set;
    }
    public virtual BinaryTreeNode Root {
        get;
        set;
    }
    public BinaryTree() {

    }
    public BinaryTree(BinaryTreeNode root) {

    }

    public virtual BinaryTreeNode GetLeftSubtree() {
        return this.Root.LeftNode;
    }

    public virtual BinaryTreeNode GetRightSubtree() {
        return this.Root.RightNode;
    }

    public virtual void GetData() {
        throw new System.NotImplementedException();
    }

    public override string ToString() {
        throw new System.NotImplementedException();
    }

}

