//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TreeNode
{
	public virtual TreeNode LeftNode
	{
		get;
		set;
	}

	public virtual TreeNode RightNode
	{
		get;
		set;
	}

	public virtual object Data
	{
		get;
		set;
	}

	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

	public TreeNode()
	{
	}

	public virtual void TreeNode()
	{
		throw new System.NotImplementedException();
	}

}

